from .linear_regression import My_Linear_Regression
from .multiple_regression import My_Multiple_Regression
from .logistic_regression import My_Logistic_Regression
from .knn import My_KNN
from .random_forest import My_Random_Forest
from .decision_tree import My_DecisionTree
from .decision_tree_reg import My_DecisionTree_Regressor
from .xgb_classifier import My_XGBClassifier
from .svm import My_SVM